vich_uploader:
    db_driver: orm
#    storage: file_system
    mappings:
            book_cover:
                uri_prefix:         '%cover_images%'
                upload_destination: '%kernel.project_dir%/%cover_images%'
                inject_on_load: true
                namer: vich_uploader.namer_uniqid
                delete_on_remove: true
                delete_on_update: true